# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutForm(object):
    def setupUi(self, AboutForm):
        AboutForm.setObjectName("AboutForm")
        AboutForm.setWindowModality(QtCore.Qt.WindowModal)
        AboutForm.resize(400, 193)
        AboutForm.setMinimumSize(QtCore.QSize(400, 193))
        AboutForm.setMaximumSize(QtCore.QSize(400, 193))
        self.label = QtWidgets.QLabel(AboutForm)
        self.label.setGeometry(QtCore.QRect(30, 20, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AboutForm)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 100, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:grey")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AboutForm)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 341, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(AboutForm)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 341, 21))
        self.label_4.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_4.setObjectName("label_4")
        self.close_PushButton = QtWidgets.QPushButton(AboutForm)
        self.close_PushButton.setGeometry(QtCore.QRect(150, 150, 100, 30))
        self.close_PushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.close_PushButton.setMaximumSize(QtCore.QSize(100, 30))
        self.close_PushButton.setObjectName("close_PushButton")

        self.retranslateUi(AboutForm)
        QtCore.QMetaObject.connectSlotsByName(AboutForm)

    def retranslateUi(self, AboutForm):
        _translate = QtCore.QCoreApplication.translate
        AboutForm.setWindowTitle(_translate("AboutForm", "About"))
        self.label.setText(_translate("AboutForm", "Sectograph"))
        self.label_2.setText(_translate("AboutForm", "0.1.0"))
        self.label_3.setText(
            _translate("AboutForm", "© 2021 *** (name is hidden by requirements)")
        )
        self.label_4.setText(_translate("AboutForm", "☆⌒(ゝ。∂)"))
        self.close_PushButton.setText(_translate("AboutForm", "Close"))
